server:
  port: 1761

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 12345
    # JPA properties
  
  jpa:
      hibernate:
        ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
      
logging:
  level:
    '[org.springframework.web]': ERROR
    com.sachin.Student: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss}- %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file: 
    name: G:/logFile/sac.log 
    